version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./site:/usr/share/nginx/html
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1111
      - MYSQL_DATABASE=web_porn
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1111
    networks:
      - mynetwork
    volumes:
      - ./data:/var/lib/mysql

networks:
  mynetwork:
